sudo: false
before_install:
- rvm install 2.2.6
- gem install dropbox-deployment
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20170106/texlive.tar.xz
  | tar -JxC $HOME/texlive
install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- tlmgr option repository ctan
- tlmgr update --self
- tlmgr install moderncv
- tlmgr install fontawesome
script:
- cd cv/
- mkdir _build
- pdflatex -halt-on-error -output-directory _build CV_en.tex
- pdflatex -halt-on-error -output-directory _build CV_fr.tex
- mkdir upload_DB
- cp _build/CV_en.pdf upload_DB/CV_en.pdf
- cp _build/CV_fr.pdf upload_DB/CV_fr.pdf
- mv upload_DB/CV_en.pdf upload_DB/$(date +%Y-%m-%d)_CV_EN.pdf
- mv upload_DB/CV_fr.pdf upload_DB/$(date +%Y-%m-%d)_CV_FR.pdf
- mv _build/CV_en.pdf _build/CV_BAUDETTE_EN.pdf
- mv _build/CV_fr.pdf _build/CV_BAUDETTE_FR.pdf
after_success:
- dropbox-deployment
deploy:
  provider: releases
  api_key:
    secure: ZhNNL7sGNkXcJZ3/qrPkbxXt1OTh93De5cRUGl4YhvrejTajFFFU8cKxKf17YNpIV3R7fXxoU2TFN37tHD8XvLJspxlTo9GJv03CrpzIYtk3fF/5ThVyiAla4sdRDRLb6YuXc1rMd+lJtHMoQ++7u3HCT6ZgznTIRqNQe8vqwbq1wRQ6s8YCjdvpTlfd7yzvumYYrpztMBEVxiH7axMc0fUfONUnzvUCb4NU6UcBwdsenkz2LPgItQl0HCjvzoLkYyQi4Oeocxh1mIAcpIVudhk6FywA9pcZSOy2CiCAaDYP4QB14lnT3Whhhj5fCo8UEVImnpiAfTeLJRnRpPrD+1l29nkzxCpJrjebv9hsotzHqbGeJqLoTM9uRGblzZtIzMQVpHHE8111sF8Ss8N+e4yoREtgTHSBuZctlI8yp28jEQCDQaGzRlY6NbxMgFuHlfroI/4q/HOP13fDAqkd3g8eP9ojh09IPmY6b1CXy509+Zrst6+mvVpqmfzjYwy7b1imGYd+wj6kJq9dKRWg37qsDIt4Tkliv84zEZTXGg07hGZh49o8/NzI1jGDqhANl09dHqJv1vgYl4F+n9N2xqdV8qt6WBkb564r6Pewe/+n2i+hU3AzlbdEhdSlZf/MxXCkdyRBusqFFHL4w0gjvNrx73wKzqr5RwW/4Z4Q3YI=
  file:
  - _build/CV_BAUDETTE_EN.pdf
  - _build/CV_BAUDETTE_FR.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: MaximeBaudette/MaximeBaudette.github.io
env:
  matrix:
    secure: AGzZbeiS4+hAcW2sigQceglRQufqiM0GlLL8SrCukEtDBO6riHDwrvXycn6U5xbJeT2JhxLUazKXIVuW0caU7wffmrEW/R2zX8kbb6La9fvRtMQBv1u3oiL5QBKNBA2UJm0uqOL5rwA57lTcBBsDqSyjdqer2YGyde+ca+/FcHJjTQxjWnYnYUbGvn30kqdnkPM9s4Cc9uKjolZ/vhNirQU260UxbnWtlIQTv4W1ViYDLrv/9U/IMevjnvDxXJQagfz1v6u2eBaU3zC/d2Y70Odn4t/bU6vpW3YsY0SxEX81gx0a3xO0sLBuPiJwSl7oFKCGKMjAEDK3JWgnEyvdTMIT+8YwNJI238DoTyGh7FbAmJkqNfieoZ10lUsD7Qc+Y+4y4Gv7juTABJrDKuUoJ24gUp4/TPljX2lD7zvZm79p+T7Y6ex1RFf4U7TtYEHIy7jUhC7vIHPCQCW9wcyV22n2Fjsct8uT6nwdEL5zUMRxW1JVkOwL+0xc3to5x4Dp664ghRu0/9ODxJHYOKOcpGKUDnPmoyx36cBsweBLmPNXdIrT567H+33CGfw6v7feYVGfuGBrK0SOSKUyialX0hLgrqCJf36fbViXna8qKZbokDaxFh+bwY9CYQYycnyeVeFwG8ETXyZ/uDFDXdS5LtMe0dddbrccr/FfE1MmKhM=
