# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            My Homepage
tagline:          ''
description:      ''
url:              http://www.baudette.fr
baseurl:          /

author:
  name:           'Maxime Baudette'
  url:            https://twitter.com/maxime44

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/maximebaudette
